name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight UTC
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub stats SVG
        run: |
          curl -o README_stats.svg "https://github-readme-stats.vercel.app/api?username=pthanushree&theme=radical&hide_border=true&count_private=true&include_all_commits=true&token=${{ secrets.GH_TOKEN }}"

      - name: Commit and push SVG
        run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git add README_stats.svg
           git diff --cached --quiet || git commit -m "Update GitHub stats"
           git push

